# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy PR

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write

# Allow one concurrent deployment
concurrency:
  group: "PR-pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@ee2113536afb7f793eed4ce60e8d3b26db912da4 # v1.127.0
        with:
          ruby-version: '3.1' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems
        env:
          ImageOS: ubuntu20
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v2
      - name: Setup Rubygems, Bundler, jekyll
        run: | 
          gem update --system --no-document
          gem update bundler --no-document
          gem install jekyll bundler
          bundle install
      - name: Build with Jekyll
        # Outputs to the './_site' directory by default
        run: bundle exec jekyll build --baseurl "/pr-preview/pr-${{github.event.number}}"
        env:
          JEKYLL_ENV: production
      - name: Check for broken links
        run: |
          bundle exec htmlproofer ./_site &> links.log
        continue-on-error: true
      - name: Archive log links
        uses: actions/upload-artifact@v1
        with:
          name: links-check.log
          path: links.log
      - uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./_site
          preview-branch: gh_pages
          umbrella-dir: pr-preview
          action: auto